# Generated by Django 2.2 on 2021-06-04 19:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210603_1526'),
        ('comment', '0002_auto_20210604_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogpost',
        ),
        migrations.AddField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(null=True, on_delete=blog.models.BlogPost, to='blog.BlogPost'),
        ),
    ]
