# Generated by Django 2.2 on 2021-08-15 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210604_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete='user.User', to=settings.AUTH_USER_MODEL),
        ),
    ]
