---
name: tests

defaults:
  run:
    shell: bash
    working-directory: ./app

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Run Tests
        run: |
          python manage.py test